project_name: mort
builds:
  - binary: mort
    goarch:
      - amd64
    goarm:
      - "6"
    goos:
      - linux
    ldflags: "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    main: "./cmd/mort/mort.go"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
release:
  github:
    name: mort
    owner: aldor007
  name_template: "{{.Tag}}"
snapshot:
  name_template: "SNAPSHOT-{{ .Commit }}"
