language: go

sudo: required
dist: bionic

go:
  - '1.12'

env:
  - LIBVIPS=8.7.4

addons:
  apt:
    update: true
    packages:
      - gobject-introspection
      - gtk-doc-tools
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - libwebp-dev
      - libbrotli-dev
      - gtk-doc
      - pkg-config
      - swig
      - automake
      - bc
         
before_install:
  - sudo apt-get install libbrotli-dev gtk-doc-tools pkg-config swig automake bc  gobject-introspection  -y
  - sudo apt-get install -y automake build-essential   gobject-introspection gtk-doc-tools libglib2.0-dev libjpeg-turbo8-dev libpng-dev 
  - sudo apt-get install -y libwebp-dev libtiff5-dev libgif-dev libexif-dev libxml2-dev libpoppler-glib-dev 
  - sudo apt-get install -y  swig libmagickwand-dev libpango1.0-dev libmatio-dev libopenslide-dev libcfitsio-dev 
  - sudo apt-get install -y libgsf-1-dev fftw3-dev liborc-0.4-dev librsvg2-dev swig 
  - wget https://github.com/libvips/libvips/archive/v$LIBVIPS.zip
  - unzip v$LIBVIPS
  - cd libvips-$LIBVIPS
  - test -f autogen.sh && ./autogen.sh || ./bootstrap.sh
  - >
    CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0
    ./configure
    --disable-debug
    --disable-dependency-tracking
    --disable-introspection
    --disable-static
    --enable-gtk-doc-html=no
    --enable-gtk-doc=no
    --enable-pyvips8=no
    --without-orc
    --without-python
    $1
  - make
  - sudo make install
  - sudo ldconfig
  
script:
  - export GO111MODULE=on
  - cd -
#  - sudo curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && sudo chmod +x /usr/local/bin/dep
#  - dep ensure -vendor-only
  - ./scripts/unit-travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
