language: go

sudo: required
dist: bionic

go:
  - '1.10'

env:
  - LIBVIPS=8.7.2

cache: apt

addons:
  apt:
    packages:
      - gobject-introspection
      - gtk-doc-tools
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - libwebp-dev
      - libbrotli-dev
      - gtk-doc

script:
  - wget https://github.com/libvips/libvips/archive/v$LIBVIPS.zip
  - unzip v$LIBVIPS
  - cd libvips-$LIBVIPS
  - test -f autogen.sh && ./autogen.sh || ./bootstrap.sh
  - >
    CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0
    ./configure
    --disable-debug
    --disable-dependency-tracking
    --disable-introspection
    --disable-static
    --enable-gtk-doc-html=no
    --enable-gtk-doc=no
    --enable-pyvips8=no
    --without-orc
    --without-python
    $1
  - make
  - sudo make install
  - sudo ldconfig

  - cd -
  - sudo curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && sudo chmod +x /usr/local/bin/dep
  - dep ensure -vendor-only
  - ./scripts/unit-travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
