FROM ghcr.io/aldor007/mort-base 

ENV GOLANG_VERSION 1.19.2
ENV TARGETARCH amd64
ARG TAG 'dev'
ARG COMMIT "master"
ARG DATE "now"


ENV WORKDIR /workspace
ENV PATH /usr/local/go/bin:$PATH
RUN rm -rf /usr/local/go && curl -fsSL --insecure "https://go.dev/dl/go$GOLANG_VERSION.linux-$TARGETARCH.tar.gz" -o golang.tar.gz \
  && tar -C /usr/local -xzf golang.tar.gz \
  && rm golang.tar.gz

WORKDIR $WORKDIR
COPY go.mod  ./
COPY go.sum ./

COPY cmd/  $WORKDIR/cmd
COPY .godir ${WORKDIR}/.godir
COPY configuration/ ${WORKDIR}/configuration
COPY etc/ ${WORKDIR}/etc
COPY pkg/ ${WORKDIR}/pkg
COPY scripts/ ${WORKDIR}/scripts
COPY Makefile ${WORKDIR}/Makefile

RUN go build -o /go/mort ./cmd/mort/mort.go
