version: '3'

services:
  redis:
    image: redis
  mort:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG=tests
        - COMMIT=master
        - DATE=now
    restart: always
    ports:
      - 8091:8091
    volumes:
      - /tmp/mort-tests:/tmp/mort-tests
      - ./tests-int/:/etc/mort/
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        - TAG=dev
        - COMMIT=master
        - DATE=now
    command: ["make", "unit"]
  integrations:
    build:
      context: .
      dockerfile: Dockerfile.integrations
    command: ["sh", "./scripts/run-tests-docker.sh"]
    environment:
      - MORT_PORT=8091
      - MORT_HOST=mort 
    volumes:
      - /tmp/mort-tests:/tmp/mort-tests:ro
    depends_on:
      - mort


