version: '3'

services:
  mort:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG=dev
        - COMMIT=master
        - DATE=now
    restart: always
    ports:
      - 8080:8080
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        - TAG=dev
        - COMMIT=master
        - DATE=now
    command: make unit
