buckets:
    local:
        keys:
          - accessKey: "acc"
            secretAccessKey: "sec"
        storages:
            basic:
                kind: "local-meta"
                rootPath: "/tmp/mort-tests/"
