headers:
  - statusCodes: [200]
    values:
      "cache-control": "max-age=84000, public"
  - statusCodes: [404, 400]
    values:
      "cache-control": "max-age=60, public"
  - statusCodes: [500, 503]
    values:
      "cache-control": "max-age=10, public"

buckets:
    media:
        keys:
          - accessKey: "acc"
            secretAccessKey: "sec"
        transform:
            path: "\\/([a-z0-9_]+)\\/(.*)"
            kind: "presets"
            order:
              parent: 1
              presetName: 0
            parentBucket: "media"
            presets:
                small:
                    quality: 75
                    filters:
                        thumbnail: {size: [150]}
                blur:
                    quality: 80
                    filters:
                        thumbnail: {size: [700]}
                        blur:
                          sigma: 5.0
                webp:
                    quality: 100
                    format: webp
                    filters:
                        thumbnail: {size: [1000]}
                watermark:
                    quality: 100
                    filters:
                        thumbnail: {size: [1300]}
                        watermark:
                            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Imgur_logo.svg/150px-Imgur_logo.svg.png"
                            position: "center-center"
                            opacity: 0.5

                gallery_big300:
                    quality: 100
                    filters:
                        thumbnail: {size: [300]}
                gallery_big200:
                    quality: 100
                    filters:
                        thumbnail: {size: [200]}
        storages:
            basic:
                kind: "http"
                url: "https://i.imgur.com/<item>"
                headers:
                  "x--key": "sec"
            transform:
                kind: "local-meta"
                rootPath: "/Users/aldor/workspace/mkaciubacom/web"
                pathPrefix: "transforms"
