buckets:
    media:
        transform:
            path: "\\/+(?:cache|resolve)\\/([a-z0-9_]+)\\/+[a-z]+\\/[a-zA-Z0-9]+\\/+(.*)"
            kind: "presets"
            presets:
                blog_small:
                    quality: 75
                    filters:
                        thumbnail: { size: [100, 70], mode: outbound }
                        interlace:
                            mode: line
                blog_medium:
                    quality: 75
                    filters:
                        thumbnail: { size: [903, 600], mode: outbound }
                        crop: { start: [0, 0], size: [900, 320] }

                blog_home:
                    quality: 75
                    filters:
                        entropy_crop: { size: [756, 396], mode: outbound }
                recent_gallery:
                    quality: 75
                    filters:
                        entropy_crop: { size: [85, 85], mode: outbound }

                promoted:
                    quality: 75
                    filters:
                        entropy_crop: { size: [896, 465], mode: outbound }

                relatedposts:
                    quality: 75
                    filters:
                        entropy_crop: { size: [504, 369], mode: outbound }

                blog_big:
                    quality: 75
                    filters:
                        auto_rotate: ~
                        strip: ~
                gallery_thumb:
                    quality: 75
                    filters:
                        thumbnail: { size: [200], mode: outbound }
                        auto_rotate: ~
                        strip: ~
                photocategory_img:
                    quality: 75
                    filters:
                        entropy_crop: { size: [600, 450], mode: outbound }
                        auto_rotate: ~
                        strip: ~
                        interlace:
                            mode: line
        storages:
            basic:
                kind: "local"
                rootPath: "/Users/aldor/workspace/mkaciubacom/web"
            transform:
                kind: "local"
                rootPath: "/Users/aldor/workspace/mkaciubacom/web"
