name: CI - Integration Test 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    container:
      image: ghcr.io/aldor007/mort-base:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHR_TOKEN }}
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git checkout 
      uses: actions/checkout@v2

    - name: Install Node JS 
      uses: actions/setup-node@v1
      with:
        node-version: 17 
    
    - name: Install npm deps
      run: npm install

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6.2 

    - name: Run the integrations tests
      run: |
        make run-test-server &
        sleep 10
        npm run tests 
        kill -9 `lsof -i:8091 -t`
      env:
        MORT_HOST: localhost 
        MORT_PORT: 8081
        CI: true